In [3]:
!pip install faker

Collecting faker
  Downloading Faker-28.1.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: python-dateutil>=2.4 in /opt/anaconda3/lib/python3.12/site-packages (from faker) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.4->faker) (1.16.0)
Downloading Faker-28.1.0-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 4.4 MB/s eta 0:00:0000:0100:01
Installing collected packages: faker
Successfully installed faker-28.1.0

In [11]:
import pandas as pd
import numpy as np
import faker

# Initialize Faker for generating fake names
fake = faker.Faker()

# Generate sample data
np.random.seed(42)
dates = pd.date_range(start="2023-01-01", end="2024-03-31", freq="D")
categories = ["cosmetics", "household", "grocery", "fastfoods", "clothes", "utensils", "gardening"]
brands = ["Brand_X", "Brand_Y", "Brand_Z"]
customer_types = ["New", "Regular"]

# Generate a list of unique fake names
unique_names = [fake.name() for _ in range(50)]  # Generate 50 unique names

data = {
    "Date": np.random.choice(dates, size=200),
    "Customer_Type": np.random.choice(customer_types, size=200),
    "Product_ID": np.random.randint(1000, 9999, size=200),  # Product ID between 1000 and 9999
    "Category": np.random.choice(categories, size=200),
    "Product_Price": np.random.uniform(10, 1000, size=200),  # Product price between 10 and 1000
    "Quantity_Sold": np.random.randint(1, 10, size=200),
    "Customer_Name": np.random.choice(unique_names, size=200),  # Use the list of unique names
    "Discount": np.random.uniform(0, 0.2, size=200),  # Discount as a fraction (0 to 20%)
    "Net_Profit": np.random.uniform(5, 500, size=200),  # Net profit between 5 and 500
    "Transaction_ID": np.random.randint(100000, 999999, size=200),  # Transaction ID between 100000 and 999999
    "Brand_Name": np.random.choice(brands, size=200)
}

# Create DataFrame
df = pd.DataFrame(data)

# Save DataFrame to CSV file
df.to_csv('generated_data.csv', index=False)

# Display the first few rows of the DataFrame in Jupyter Notebook
df.head()

,Date,Customer_Type,Product_ID,Category,Product_Price,Quantity_Sold,Customer_Name,Discount,Net_Profit,Transaction_ID,Brand_Name
0,2023-04-13,Regular,5911,cosmetics,286.965872,6,Sarah Buchanan,0.027364,484.594538,869299,Brand_Z
1,2024-03-11,Regular,4987,grocery,417.094654,2,Randy Horne,0.190047,376.077657,965962,Brand_X
2,2023-12-15,Regular,7015,fastfoods,606.754063,8,David Scott,0.089201,69.392689,516715,Brand_Z
3,2023-09-28,Regular,2218,household,278.248066,5,Teresa Golden,0.037027,380.340282,471000,Brand_Z
4,2023-04-17,Regular,5496,cosmetics,141.853274,7,Tyler Ramos,0.108380,17.170524,313567,Brand_Z